const Constants = {
	PAGE_LOADING: 'PAGE_LOADING',
	PAGE_SUCCESSED: 'PAGE_SUCCESSED',
	PAGE_FAILED: 'PAGE_FAILED',

	SET_ADDRESS: 'SET_ADDRESS',
	SET_CCO_BALANCE: 'SET_CCO_BALANCE',
	SET_REFERRER_ADDRESS: 'SET_REFERRER_ADDRESS',
	SET_WITHDRAWABLE: 'SET_WITHDRAWABLE',
	SET_ALLOWED: 'SET_ALLOWED',
	SET_BALANCE_OF: 'SET_BALANCE_OF',
	SET_GAME_INFO: 'SET_GAME_INFO',
	SET_MY_GAME: 'SET_MY_GAME',
	SET_URL_REF: 'SET_URL_REF',
	SET_REFERAL_INFO: 'SET_REFERAL_INFO',

	TXN_HISTORY_URL:
		'https://api-ropsten.etherscan.io/api?module=account&action=txlist&address={ADDRESS}&startblock=0&endblock=9999999999999&sort=desc&apikey=',

	TETHER_TOKEN: '0xB38f7Dc91D9e4B6Ff10e0f7772Ef16a259b92EbE', // usdt
	TEST_TOKEN: '0x9F457D0ec395FbBDa1126d9E72503dDC23858749', // cco
	EXCHANGE: '0xDF511553b06d7B86FA8eB367E107d1b593f0ed95', // exchange
	TEST_GAME: '0xA86E1aC3D2aFb772b5477BbdD1d2C0688F6046Ba', // x2play

	TETHER_TOKEN_ABI: [
		{
			constant: true,
			inputs: [],
			name: 'name',
			outputs: [{ name: '', type: 'string' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ name: '_upgradedAddress', type: 'address' }],
			name: 'deprecate',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ name: '_spender', type: 'address' },
				{ name: '_value', type: 'uint256' },
			],
			name: 'approve',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'deprecated',
			outputs: [{ name: '', type: 'bool' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ name: '_evilUser', type: 'address' }],
			name: 'addBlackList',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'totalSupply',
			outputs: [{ name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ name: '_from', type: 'address' },
				{ name: '_to', type: 'address' },
				{ name: '_value', type: 'uint256' },
			],
			name: 'transferFrom',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'upgradedAddress',
			outputs: [{ name: '', type: 'address' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ name: '', type: 'address' }],
			name: 'balances',
			outputs: [{ name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'decimals',
			outputs: [{ name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'maximumFee',
			outputs: [{ name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: '_totalSupply',
			outputs: [{ name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [],
			name: 'unpause',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ name: '_maker', type: 'address' }],
			name: 'getBlackListStatus',
			outputs: [{ name: '', type: 'bool' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [
				{ name: '', type: 'address' },
				{ name: '', type: 'address' },
			],
			name: 'allowed',
			outputs: [{ name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'paused',
			outputs: [{ name: '', type: 'bool' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ name: 'who', type: 'address' }],
			name: 'balanceOf',
			outputs: [{ name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [],
			name: 'pause',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'getOwner',
			outputs: [{ name: '', type: 'address' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'owner',
			outputs: [{ name: '', type: 'address' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'symbol',
			outputs: [{ name: '', type: 'string' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ name: '_to', type: 'address' },
				{ name: '_value', type: 'uint256' },
			],
			name: 'transfer',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ name: 'newBasisPoints', type: 'uint256' },
				{ name: 'newMaxFee', type: 'uint256' },
			],
			name: 'setParams',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ name: 'amount', type: 'uint256' }],
			name: 'issue',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ name: 'amount', type: 'uint256' }],
			name: 'redeem',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [
				{ name: '_owner', type: 'address' },
				{ name: '_spender', type: 'address' },
			],
			name: 'allowance',
			outputs: [{ name: 'remaining', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'basisPointsRate',
			outputs: [{ name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ name: '', type: 'address' }],
			name: 'isBlackListed',
			outputs: [{ name: '', type: 'bool' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ name: '_clearedUser', type: 'address' }],
			name: 'removeBlackList',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'MAX_UINT',
			outputs: [{ name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ name: 'newOwner', type: 'address' }],
			name: 'transferOwnership',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ name: '_blackListedUser', type: 'address' }],
			name: 'destroyBlackFunds',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			inputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'constructor',
		},
		{
			anonymous: false,
			inputs: [{ indexed: false, name: 'amount', type: 'uint256' }],
			name: 'Issue',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [{ indexed: false, name: 'amount', type: 'uint256' }],
			name: 'Redeem',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [{ indexed: false, name: 'newAddress', type: 'address' }],
			name: 'Deprecate',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: false, name: 'feeBasisPoints', type: 'uint256' },
				{ indexed: false, name: 'maxFee', type: 'uint256' },
			],
			name: 'Params',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: false, name: '_blackListedUser', type: 'address' },
				{ indexed: false, name: '_balance', type: 'uint256' },
			],
			name: 'DestroyedBlackFunds',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [{ indexed: false, name: '_user', type: 'address' }],
			name: 'AddedBlackList',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [{ indexed: false, name: '_user', type: 'address' }],
			name: 'RemovedBlackList',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, name: 'owner', type: 'address' },
				{ indexed: true, name: 'spender', type: 'address' },
				{ indexed: false, name: 'value', type: 'uint256' },
			],
			name: 'Approval',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, name: 'from', type: 'address' },
				{ indexed: true, name: 'to', type: 'address' },
				{ indexed: false, name: 'value', type: 'uint256' },
			],
			name: 'Transfer',
			type: 'event',
		},
		{ anonymous: false, inputs: [], name: 'Pause', type: 'event' },
		{ anonymous: false, inputs: [], name: 'Unpause', type: 'event' },
	],

	TEST_TOKEN_ABI: [
		{
			inputs: [
				{ internalType: 'address', name: 'initialOwner', type: 'address' },
			],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'constructor',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: true,
					internalType: 'address',
					name: 'owner',
					type: 'address',
				},
				{
					indexed: true,
					internalType: 'address',
					name: 'spender',
					type: 'address',
				},
				{
					indexed: false,
					internalType: 'uint256',
					name: 'value',
					type: 'uint256',
				},
			],
			name: 'Approval',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: true,
					internalType: 'address',
					name: 'previousOwner',
					type: 'address',
				},
				{
					indexed: true,
					internalType: 'address',
					name: 'newOwner',
					type: 'address',
				},
			],
			name: 'OwnershipTransferred',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: true,
					internalType: 'address',
					name: 'from',
					type: 'address',
				},
				{ indexed: true, internalType: 'address', name: 'to', type: 'address' },
				{
					indexed: false,
					internalType: 'uint256',
					name: 'value',
					type: 'uint256',
				},
			],
			name: 'Transfer',
			type: 'event',
		},
		{
			constant: true,
			inputs: [
				{ internalType: 'address', name: 'owner', type: 'address' },
				{ internalType: 'address', name: 'spender', type: 'address' },
			],
			name: 'allowance',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'address', name: 'spender', type: 'address' },
				{ internalType: 'uint256', name: 'amount', type: 'uint256' },
			],
			name: 'approve',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'address', name: 'spender', type: 'address' },
				{ internalType: 'uint256', name: 'amount', type: 'uint256' },
				{ internalType: 'bytes', name: 'extraData', type: 'bytes' },
			],
			name: 'approveAndCall',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
			name: 'balanceOf',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
			name: 'burn',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'address', name: 'account', type: 'address' },
				{ internalType: 'uint256', name: 'amount', type: 'uint256' },
			],
			name: 'burnFrom',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'decimals',
			outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'address', name: 'spender', type: 'address' },
				{ internalType: 'uint256', name: 'subtractedValue', type: 'uint256' },
			],
			name: 'decreaseAllowance',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'bool', name: 'check', type: 'bool' }],
			name: 'finishMinting',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'address', name: 'spender', type: 'address' },
				{ internalType: 'uint256', name: 'addedValue', type: 'uint256' },
			],
			name: 'increaseAllowance',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
			name: 'isMinter',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
			name: 'isRegistered',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'address', name: 'to', type: 'address' },
				{ internalType: 'uint256', name: 'value', type: 'uint256' },
			],
			name: 'mint',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'minter',
			outputs: [{ internalType: 'address', name: '', type: 'address' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'mintingFinished',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'name',
			outputs: [{ internalType: 'string', name: '', type: 'string' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'owner',
			outputs: [{ internalType: 'address', name: '', type: 'address' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
			name: 'registerContract',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
			name: 'setMinter',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'symbol',
			outputs: [{ internalType: 'string', name: '', type: 'string' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'totalSupply',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'address', name: 'to', type: 'address' },
				{ internalType: 'uint256', name: 'value', type: 'uint256' },
			],
			name: 'transfer',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'address', name: 'sender', type: 'address' },
				{ internalType: 'address', name: 'recipient', type: 'address' },
				{ internalType: 'uint256', name: 'amount', type: 'uint256' },
			],
			name: 'transferFrom',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
			name: 'transferOwnership',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
			name: 'unregisterContract',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'address', name: 'ERC20Token', type: 'address' },
				{ internalType: 'address', name: 'recipient', type: 'address' },
			],
			name: 'withdrawERC20',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
	],

	EXCHANGE_ABI: [
		{
			inputs: [
				{ internalType: 'address', name: 'USDTAddr', type: 'address' },
				{ internalType: 'address', name: 'CCOAddr', type: 'address' },
				{ internalType: 'address', name: 'initialOwner', type: 'address' },
				{ internalType: 'address', name: 'initialWallet', type: 'address' },
			],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'constructor',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: true,
					internalType: 'address',
					name: 'previousOwner',
					type: 'address',
				},
				{
					indexed: true,
					internalType: 'address',
					name: 'newOwner',
					type: 'address',
				},
			],
			name: 'OwnershipTransferred',
			type: 'event',
		},
		{
			constant: true,
			inputs: [],
			name: 'CCO',
			outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'USDT',
			outputs: [{ internalType: 'contract IUSDT', name: '', type: 'address' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'address', name: 'from', type: 'address' },
				{ internalType: 'uint256', name: 'amount', type: 'uint256' },
				{ internalType: 'address', name: 'referrer', type: 'address' },
			],
			name: 'exchangeCCOtoUSDT',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'address', name: 'from', type: 'address' },
				{ internalType: 'uint256', name: 'amount', type: 'uint256' },
				{ internalType: 'address', name: 'referrer', type: 'address' },
			],
			name: 'exchangeUSDTtoCCO',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [
				{ internalType: 'address', name: 'account', type: 'address' },
				{ internalType: 'uint256', name: 'from', type: 'uint256' },
				{ internalType: 'uint256', name: 'to', type: 'uint256' },
			],
			name: 'getReferralInfo',
			outputs: [
				{ internalType: 'address[]', name: 'referrals', type: 'address[]' },
				{ internalType: 'uint256[]', name: 'bonuses', type: 'uint256[]' },
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
			name: 'getReferrerInfo',
			outputs: [
				{ internalType: 'address', name: 'referrer', type: 'address' },
				{ internalType: 'uint256', name: 'rate', type: 'uint256' },
				{ internalType: 'uint256', name: 'amountOfReferrals', type: 'uint256' },
				{ internalType: 'uint256', name: 'totalBonuses', type: 'uint256' },
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'isOwner',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'owner',
			outputs: [{ internalType: 'address', name: '', type: 'address' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'address', name: 'from', type: 'address' },
				{ internalType: 'uint256', name: 'amount', type: 'uint256' },
				{ internalType: 'address', name: 'token', type: 'address' },
				{ internalType: 'bytes', name: 'extraData', type: 'bytes' },
			],
			name: 'receiveApproval',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [],
			name: 'renounceOwnership',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'address', name: 'ref', type: 'address' },
				{ internalType: 'uint256', name: 'rate', type: 'uint256' },
			],
			name: 'setReferrer',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
			name: 'transferOwnership',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ internalType: 'address', name: '', type: 'address' }],
			name: 'users',
			outputs: [
				{ internalType: 'uint256', name: 'rate', type: 'uint256' },
				{ internalType: 'address', name: 'referrer', type: 'address' },
				{ internalType: 'uint256', name: 'totalBonuses', type: 'uint256' },
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'wallet',
			outputs: [{ internalType: 'address', name: '', type: 'address' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'address', name: 'ERC20Token', type: 'address' },
				{ internalType: 'address', name: 'recipient', type: 'address' },
			],
			name: 'withdrawERC20',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
	],

	TEST_GAME_ABI: [
		{
			inputs: [
				{ internalType: 'address', name: 'token', type: 'address' },
				{ internalType: 'uint256', name: 'vol', type: 'uint256' },
			],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'constructor',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: true,
					internalType: 'address',
					name: 'previousOwner',
					type: 'address',
				},
				{
					indexed: true,
					internalType: 'address',
					name: 'newOwner',
					type: 'address',
				},
			],
			name: 'OwnershipTransferred',
			type: 'event',
		},
		{
			constant: true,
			inputs: [],
			name: 'CCO',
			outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'getAmountOfRounds',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [
				{ internalType: 'address', name: 'account', type: 'address' },
				{ internalType: 'uint256', name: 'i', type: 'uint256' },
			],
			name: 'getBatch',
			outputs: [
				{ internalType: 'uint256', name: 'index', type: 'uint256' },
				{ internalType: 'uint256', name: 'amount', type: 'uint256' },
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'getCurrentGameInfo',
			outputs: [
				{ internalType: 'uint256', name: '_cycle', type: 'uint256' },
				{ internalType: 'uint256', name: 'round', type: 'uint256' },
				{ internalType: 'uint256', name: 'bets', type: 'uint256' },
				{ internalType: 'uint256', name: 'players', type: 'uint256' },
				{ internalType: 'uint256', name: 'volume', type: 'uint256' },
				{ internalType: 'uint256', name: 'filled', type: 'uint256' },
				{ internalType: 'uint256', name: 'available', type: 'uint256' },
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [
				{ internalType: 'uint256', name: '_cycle', type: 'uint256' },
				{ internalType: 'uint256', name: 'from', type: 'uint256' },
				{ internalType: 'uint256', name: 'to', type: 'uint256' },
			],
			name: 'getGamesInfo',
			outputs: [
				{ internalType: 'uint256[]', name: 'bets', type: 'uint256[]' },
				{ internalType: 'uint256[]', name: 'players', type: 'uint256[]' },
				{ internalType: 'uint256[]', name: 'volume', type: 'uint256[]' },
				{ internalType: 'uint256[]', name: 'filled', type: 'uint256[]' },
				{ internalType: 'uint256[]', name: 'available', type: 'uint256[]' },
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
			name: 'getInsurance',
			outputs: [
				{ internalType: 'uint256', name: 'insurance', type: 'uint256' },
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ internalType: 'uint256', name: 'index', type: 'uint256' }],
			name: 'getParameters',
			outputs: [
				{ internalType: 'uint256', name: 'volume', type: 'uint256' },
				{ internalType: 'uint256', name: 'filled', type: 'uint256' },
				{ internalType: 'uint256', name: 'available', type: 'uint256' },
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [
				{ internalType: 'address', name: 'account', type: 'address' },
				{ internalType: 'uint256', name: 'from', type: 'uint256' },
				{ internalType: 'uint256', name: 'to', type: 'uint256' },
			],
			name: 'getUserGames',
			outputs: [
				{ internalType: 'uint256[]', name: '_cycle', type: 'uint256[]' },
				{ internalType: 'uint256[]', name: 'round', type: 'uint256[]' },
				{ internalType: 'uint256[]', name: 'start', type: 'uint256[]' },
				{ internalType: 'uint256[]', name: 'finish', type: 'uint256[]' },
				{ internalType: 'uint256[]', name: 'totalBets', type: 'uint256[]' },
				{ internalType: 'uint256[]', name: 'totalPlayers', type: 'uint256[]' },
				{ internalType: 'uint256[]', name: 'profit', type: 'uint256[]' },
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
			name: 'getUserStats',
			outputs: [
				{ internalType: 'uint256', name: 'totalBets', type: 'uint256' },
				{ internalType: 'uint256', name: 'totalProfit', type: 'uint256' },
				{ internalType: 'uint256', name: 'totalWithdrawn', type: 'uint256' },
				{ internalType: 'uint256', name: 'totalWithdrawable', type: 'uint256' },
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
			name: 'getWithdrawable',
			outputs: [
				{ internalType: 'uint256', name: 'withdrawable', type: 'uint256' },
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
			name: 'getWithdrawn',
			outputs: [
				{ internalType: 'uint256', name: 'withdrawable', type: 'uint256' },
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'address', name: 'from', type: 'address' },
				{ internalType: 'uint256', name: 'amount', type: 'uint256' },
			],
			name: 'invest',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'isStarted',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: true,
			inputs: [],
			name: 'owner',
			outputs: [{ internalType: 'address', name: '', type: 'address' }],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [
				{ internalType: 'address', name: 'from', type: 'address' },
				{ internalType: 'uint256', name: 'amount', type: 'uint256' },
				{ internalType: 'address', name: 'token', type: 'address' },
				{ internalType: 'bytes', name: 'extraData', type: 'bytes' },
			],
			name: 'receiveApproval',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
			name: 'reinvest',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'uint256', name: 'start', type: 'uint256' }],
			name: 'restart',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
			name: 'transferOwnership',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			constant: true,
			inputs: [{ internalType: 'address', name: '', type: 'address' }],
			name: 'users',
			outputs: [
				{ internalType: 'uint256', name: 'withdrawn', type: 'uint256' },
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			constant: false,
			inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
			name: 'withdraw',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
	],
};

export default Constants;
